wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.6.9
    start_time: 1661823262.830553
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 7
      - 23
      4: 3.6.9
      5: 0.13.2
      8:
      - 5
args/accelerator:
  desc: null
  value: None
args/accumulate_grad_batches:
  desc: null
  value: None
args/amp_backend:
  desc: null
  value: native
args/amp_level:
  desc: null
  value: None
args/auto_lr_find:
  desc: null
  value: false
args/auto_scale_batch_size:
  desc: null
  value: false
args/auto_select_gpus:
  desc: null
  value: false
args/batch_size:
  desc: null
  value: 1
args/benchmark:
  desc: null
  value: false
args/check_val_every_n_epoch:
  desc: null
  value: 1
args/checkpoint_callback:
  desc: null
  value: None
args/default_root_dir:
  desc: null
  value: None
args/detect_anomaly:
  desc: null
  value: false
args/deterministic:
  desc: null
  value: false
args/devices:
  desc: null
  value: None
args/enable_checkpointing:
  desc: null
  value: true
args/enable_model_summary:
  desc: null
  value: true
args/enable_progress_bar:
  desc: null
  value: true
args/fast_dev_run:
  desc: null
  value: false
args/flush_logs_every_n_steps:
  desc: null
  value: None
args/gpus:
  desc: null
  value: 1
args/gradient_clip_algorithm:
  desc: null
  value: None
args/gradient_clip_val:
  desc: null
  value: None
args/ipus:
  desc: null
  value: None
args/learning_rate:
  desc: null
  value: 0.0003
args/limit:
  desc: null
  value: 100
args/limit_predict_batches:
  desc: null
  value: 1.0
args/limit_test_batches:
  desc: null
  value: 1.0
args/limit_train_batches:
  desc: null
  value: 1.0
args/limit_val_batches:
  desc: null
  value: 1.0
args/log_every_n_steps:
  desc: null
  value: 50
args/log_gpu_memory:
  desc: null
  value: None
args/logger:
  desc: null
  value: true
args/max_epochs:
  desc: null
  value: None
args/max_steps:
  desc: null
  value: -1
args/max_time:
  desc: null
  value: None
args/min_epochs:
  desc: null
  value: None
args/min_steps:
  desc: null
  value: None
args/move_metrics_to_cpu:
  desc: null
  value: false
args/multiple_trainloader_mode:
  desc: null
  value: max_size_cycle
args/num_nodes:
  desc: null
  value: 1
args/num_processes:
  desc: null
  value: 1
args/num_sanity_val_steps:
  desc: null
  value: 2
args/overfit_batches:
  desc: null
  value: 0.0
args/plugins:
  desc: null
  value: None
args/precision:
  desc: null
  value: 32
args/prepare_data_per_node:
  desc: null
  value: None
args/process_position:
  desc: null
  value: 0
args/profiler:
  desc: null
  value: None
args/progress_bar_refresh_rate:
  desc: null
  value: None
args/reload_dataloaders_every_epoch:
  desc: null
  value: false
args/reload_dataloaders_every_n_epochs:
  desc: null
  value: 0
args/replace_sampler_ddp:
  desc: null
  value: true
args/resume_from_checkpoint:
  desc: null
  value: None
args/stochastic_weight_avg:
  desc: null
  value: false
args/strategy:
  desc: null
  value: None
args/sync_batchnorm:
  desc: null
  value: false
args/terminate_on_nan:
  desc: null
  value: None
args/test_size:
  desc: null
  value: 0.15
args/tpu_cores:
  desc: null
  value: None
args/track_grad_norm:
  desc: null
  value: -1
args/val_check_interval:
  desc: null
  value: 1.0
args/weight_decay:
  desc: null
  value: 0.0003
args/weights_save_path:
  desc: null
  value: None
args/weights_summary:
  desc: null
  value: top
num_classes:
  desc: null
  value: 10
